export enum RoleEnum {

    CREDENTIAL_SEARCH = 'USUARIO_CONSULTAR',
    CREDENTIAL_CREATE = 'USUARIO_CADASTRAR',
    CREDENTIAL_EDIT = 'USUARIO_EDITAR',
    CREDENTIAL_VIEW = 'USUARIO_VISUALIZAR',
    CREDENTIAL_ACTIVATE = 'USUARIO_ATIVAR',
    CREDENTIAL_INACTIVATE = 'USUARIO_INATIVAR',
    CREDENTIAL_DELETE = 'USUARIO_EXCLUIR',
    CREDENTIAL_SELF_DATA = 'USUARIO_AUTO_EDICAO',
    CREDENTIAL_INTERNAL_SEARCH = 'USUARIO_INTERNO_CONSULTAR',
    CREDENTIAL_INTERNAL_VIEW = 'USUARIO_INTERNO_VISUALIZAR',
    LOG_SEARCH_CREDENTIAL = 'LOG_CONSULTAR_USUARIO',

    AUDIT_ALL = 'AUDIT_ALL'

}
